import {
    CiCalendar, CiCreditCard1, CiDatabase, CiFacebook,
    CiFlag1, CiLinkedin, CiLock, CiMicrochip, CiPalette, CiPower,
    CiReceipt, CiSettings, CiSliderHorizontal, CiStar,
    CiUnlock, CiUser, CiWallet, CiWarning,
} from "react-icons/ci";
import {
    PiBellRingingLight, PiBriefcaseLight, PiChartLineUpLight,
    PiChatCircleDotsLight, PiCheck, PiClipboardTextLight,
    PiCompassRoseLight, PiEnvelopeOpenLight, PiFigmaLogoLight, PiGithubLogoLight,
    PiHeadphonesLight, PiHouseLight, PiImagesLight, PiInfoLight, PiInstagramLogoLight, PiKanbanLight,
    PiLinkLight, PiNotebookLight, PiPaperPlaneTiltLight, PiPinterestLogoLight,
    PiRedditLogoLight, PiShapesLight, PiShieldCheckeredLight,
    PiTiktokLogoLight, PiTrashLight, PiVideoCameraLight, PiXLogoLight,
    PiYoutubeLogoLight
} from "react-icons/pi";

export const pricingCards = [
    {
        title: 'Basic',
        description: 'Get started with Opus',
        price: 'Free',
        duration: '',
        highlight: 'Key Features',
        features: [
            'Basic one-page portfolio',
            'Basic contact management',
            'Simple task tracking',
            'Limited time logging',
            '5 invoices per month',
            '2 GB file storage',
        ],
        priceId: ''
    },
    {
        title: 'Ultimate',
        description: 'The ultimate freelancing kit',
        price: '$49',
        duration: 'month',
        highlight: 'Key Features',
        features: [
            'Customizable multi-page portfolio',
            'Analytics and reporting',
            'Comprehensive project management',
            'Integrate with third-party apps',
            'Custom invoice templates',
            'Automated payment reminders',
            'Tax prep and forecasting',
            'Unlimited file storage',
        ],
        priceId: 'price_5s4vyf751ecs7os'
    },
    {
        title: 'Premium',
        description: 'The ultimate freelancing kit',
        price: '$29',
        duration: 'month',
        highlight: 'Key Features',
        features: [
            'Advanced portfolio customization',
            'CRM follow-ups and reminders',
            'Enhanced task management',
            'Unlimited time entries',
            'Unlimited invoices',
            'Basic expense tracking',
            'Financial reporting',
            '20 GB file storage',
        ],
        priceId: 'price_pxzapqw3zkv8lzv'
    },
];

export const States = [
    {value: 'Alabama', label: 'Alabama'},
    {value: 'Alaska', label: 'Alaska'},
    {value: 'Arizona', label: 'Arizona'},
    {value: 'Arkansas', label: 'Arkansas'},
    {value: 'California', label: 'California'},
    {value: 'Colorado', label: 'Colorado'},
    {value: 'Connecticut', label: 'Connecticut'},
    {value: 'Delaware', label: 'Delaware'},
    {value: 'Florida', label: 'Florida'},
    {value: 'Georgia', label: 'Georgia'},
    {value: 'Hawaii', label: 'Hawaii'},
    {value: 'Idaho', label: 'Idaho'},
    {value: 'Illinois', label: 'Illinois'},
    {value: 'Indiana', label: 'Indiana'},
    {value: 'Iowa', label: 'Iowa'},
    {value: 'Kansas', label: 'Kansas'},
    {value: 'Kentucky', label: 'Kentucky'},
    {value: 'Louisiana', label: 'Louisiana'},
    {value: 'Maine', label: 'Maine'},
    {value: 'Maryland', label: 'Maryland'},
    {value: 'Massachusetts', label: 'Massachusetts'},
    {value: 'Michigan', label: 'Michigan'},
    {value: 'Minnesota', label: 'Minnesota'},
    {value: 'Mississippi', label: 'Mississippi'},
    {value: 'Missouri', label: 'Missouri'},
    {value: 'Montana', label: 'Montana'},
    {value: 'Nebraska', label: 'Nebraska'},
    {value: 'Nevada', label: 'Nevada'},
    {value: 'New Hampshire', label: 'New Hampshire'},
    {value: 'New Jersey', label: 'New Jersey'},
    {value: 'New Mexico', label: 'New Mexico'},
    {value: 'New York', label: 'New York'},
    {value: 'North Carolina', label: 'North Carolina'},
    {value: 'North Dakota', label: 'North Dakota'},
    {value: 'Ohio', label: 'Ohio'},
    {value: 'Oklahoma', label: 'Oklahoma'},
    {value: 'Oregon', label: 'Oregon'},
    {value: 'Pennsylvania', label: 'Pennsylvania'},
    {value: 'Rhode Island', label: 'Rhode Island'},
    {value: 'South Carolina', label: 'South Carolina'},
    {value: 'South Dakota', label: 'South Dakota'},
    {value: 'Tennessee', label: 'Tennessee'},
    {value: 'Texas', label: 'Texas'},
    {value: 'Utah', label: 'Utah'},
    {value: 'Vermont', label: 'Vermont'},
    {value: 'Virginia', label: 'Virginia'},
    {value: 'Washington', label: 'Washington'},
    {value: 'West Virginia', label: 'West Virginia'},
    {value: 'Wisconsin', label: 'Wisconsin'},
    {value: 'Wyoming', label: 'Wyoming'},
    {value: 'American Samoa', label: 'American Samoa'},
    {value: 'Guam', label: 'Guam'},
    {value: 'Northern Mariana Islands', label: 'Northern Mariana Islands'},
    {value: 'Puerto Rico', label: 'Puerto Rico'},
    {value: 'Virgin Islands', label: 'Virgin Islands'},
    {value: 'District of Columbia', label: 'District of Columbia'},
]

export const Icons = [
    {
        value: 'settings',
        label: 'Settings',
        path: CiSettings,
    },
    {
        value: 'chart',
        label: 'Chart',
        path: PiChartLineUpLight,
    },
    {
        value: 'calendar',
        label: 'Calendar',
        path: CiCalendar,
    },
    {
        value: 'check',
        label: 'Check',
        path: PiCheck,
    },
    {
        value: 'chip',
        label: 'Chip',
        path: CiMicrochip,
    },
    {
        value: 'compass',
        label: 'Compass',
        path: PiCompassRoseLight,
    },
    {
        value: 'database',
        label: 'Database',
        path: CiDatabase,
    },
    {
        value: 'flag',
        label: 'Flag',
        path: CiFlag1,
    },
    {
        value: 'home',
        label: 'Home',
        path: PiHouseLight,
    },
    {
        value: 'info',
        label: 'Info',
        path: PiInfoLight,
    },
    {
        value: 'link',
        label: 'Link',
        path: PiLinkLight,
    },
    {
        value: 'lock',
        label: 'Lock',
        path: CiLock,
    },
    {
        value: 'unlock',
        label: 'UnLock',
        path: CiUnlock,
    },
    {
        value: 'messages',
        label: 'Messages',
        path: PiChatCircleDotsLight,
    },
    {
        value: 'category',
        label: 'Category',
        path: PiShapesLight,
    },
    {
        value: 'clipboard',
        label: 'Clipboard',
        path: PiClipboardTextLight,
    },
    {
        value: 'payment',
        label: 'Payment',
        path: CiCreditCard1,
    },
    {
        value: 'wallet',
        label: 'Wallet',
        path: CiWallet,
    },
    {
        value: 'person',
        label: 'Person',
        path: CiUser,
    },
    {
        value: 'shield',
        label: 'Shield',
        path: PiShieldCheckeredLight,
    },
    {
        value: 'headphones',
        label: 'Headphones',
        path: PiHeadphonesLight,
    },
    {
        value: 'mail',
        label: 'Mail',
        path: PiEnvelopeOpenLight,
    },
    {
        value: 'notification',
        label: 'Notification',
        path: PiBellRingingLight,
    },
    {
        value: 'power',
        label: 'Power',
        path: CiPower,
    },
    {
        value: 'receipt',
        label: 'Receipt',
        path: CiReceipt,
    },
    {
        value: 'send',
        label: 'Send',
        path: PiPaperPlaneTiltLight,
    },
    {
        value: 'star',
        label: 'Star',
        path: CiStar,
    },
    {
        value: 'tune',
        label: 'Tune',
        path: CiSliderHorizontal,
    },
    {
        value: 'video',
        label: 'Video',
        path: PiVideoCameraLight,
    },
    {
        value: 'media',
        label: 'Media',
        path: PiImagesLight,
    },
    {
        value: 'kanban',
        label: 'Kanban',
        path: PiKanbanLight,
    },
    {
        value: 'portfolio',
        label: 'Portfolio',
        path: PiNotebookLight,
    },
    {
        value: 'chip',
        label: 'Chip',
        path: CiMicrochip,
    },
    {
        value: 'warning',
        label: 'Warning',
        path: CiWarning,
    },
    {
        value: 'linkedin',
        label: 'LinkedIn',
        path: CiLinkedin,
    },
    {
        value: 'facebook',
        label: 'Facebook',
        path: CiFacebook,
    },
    {
        value: 'instagram',
        label: 'Instagram',
        path: PiInstagramLogoLight,
    },
    {
        value: 'github',
        label: 'Github',
        path: PiGithubLogoLight,
    },
    {
        value: 'twitterX',
        label: 'TwitterX',
        path: PiXLogoLight,
    },
    {
        value: 'youtube',
        label: 'YouTube',
        path: PiYoutubeLogoLight,
    },
    {
        value: 'tiktok',
        label: 'TikTok',
        path: PiTiktokLogoLight,
    },
    {
        value: 'reddit',
        label: 'Reddit',
        path: PiRedditLogoLight,
    },
    {
        value: 'pinterest',
        label: 'Pinterest',
        path: PiPinterestLogoLight,
    },
    {
        value: 'figma',
        label: 'Figma',
        path: PiFigmaLogoLight,
    },
    {
        value: 'trash',
        label: 'Trash',
        path: PiTrashLight,
    },
    {
        value: 'briefcase',
        label: 'Briefcase',
        path: PiBriefcaseLight,
    },
    {
        value: 'palette',
        label: 'Palette',
        path: CiPalette,
    },
]